### ISSUE TITLE
MassUpdateResultInterface Document getErrors()

### ISSUE THREAD

**Issue by amenk** [SC-Networks/evalanche-soap-api-connector#109]
When doing a mass update we get some errors.

Array content is just integers .. What does it mean? How can we find out what the error was?

**Comment by amenk** [comment]
I found the information on https://scnem2.com/servicecenter/developers/webservices/soap/soap_v0.html

It's the list of records-indices that had an error.

It's a pity that the actual error message / code is not returned here.

**Comment by usox** [comment]
Hi @amenk.

Yep, you're right - the result should definitely contain more detailed information about the error itself. Sadly, we can't extend the result, because:
- We don't collect those informations in a way we could safely expose them to the public atm
- We can't alter the massresult return scheme without breaking BC

In future, the profile namespace will be re-implemented in a new version of the soap api - so we will have the chance to correct some ugliness from the past. But we don't have an ETA for this.

Least we can do atm is updating the internal php-docblock of the method. SC-Networks/evalanche-soap-api-struct#37

**Comment by amenk** [comment]
Okay, lets change the doc block.

One error reason can be (after hours of guesswork), that the field count in some entries is different from the header.
