### ISSUE TITLE
How to work with jobHandles

### ISSUE THREAD

**Issue by s1de21** [SC-Networks/evalanche-soap-api-connector#128]
Hey,

i already saw the struct repo and the definition of the jobHandle and jobResult but i don't understand it.

When i call it i get the expected result descriped in the jobHanlder Struct but how to deal with it and get the actual results.

Hope someone can give me an example or a hint.

Thank you!

**Comment by usox** [comment]
Hi @s1de21 

The JobHandle contains two crucial informations about the job: `id` and `status`.
- Id: represents the identifier for your asynchronous job
- status: represents the current state of the background job

The state can be one of the following:
- 0: queued
- 1: at work
- 2: finished
- 3: temporary error (retry pending)
- 4: permanent error

After you've got your JobHandle, you can use the id as param for the `getJobInformation` method in the namespace to check, if your job has already been processed.
If your job has been finished, you can use the `getResults` method (again with the JobHandle id as parameter) to retrieve the results.

But beware:
Results of asynchronous request can get very huge (that's why they are asynchronous) - so we split the result in chunks. The `result_chunks` property in the JobHandle result tells you the amount of chunks you have to pull in row.
If `result_chunks` is 1, you have to call `getResults` once. If it's >1, you have to call the method that amount of times. Every time, getResults is called, it will set the internal chunk pointer one step forward - so you have to perform these calls sequentially.

I hope, I was able to enlighten you :)

We will add these informations to the documentation...

**Comment by s1de21** [comment]
Hey, thank you for your answer! Can you tell how to access the getJobInfirmation? This does not work..

$userList = $connection->createJobClient()->getJobInformation("xxx");
$userList = $connection->createJobHandleClient()->getJobInformation("xxx");
$userList = $connection->createJobHandlerClient()->getJobInformation("xxx");
$userList = $connection->createProfileClient()->getJobInformation("xxx");

**Comment by usox** [comment]
Well, just have a look at the available methods in the ProfileClient.

```
$jobInformation = $connection->createProfileClient()->getJobInformationByJobId('xxx');
$result_chunk = $connection->createProfileClient()->getResultByJobId('xxx')
```

**Comment by s1de21** [comment]
Thank you!
