### ISSUE TITLE
Folder delete() doesn't return a boolean

### ISSUE THREAD

**Issue by danielneubert** [SC-Networks/evalanche-soap-api-connector#138]
Just came across the fact that the folder (category) method `delete()` doesn't return a boolean value. (In the Connector and in the original SOAP API).

Is there reason for that? Currently you have to send a `delete()` request followed by a `get()` request and catch the error if everything went right. Not that elegant especially for the tricky folder deletion. (Everything within it must be deleted before)

May there be a possibility to "fix" / update this?

**Comment by usox** [comment]
Hi @danielneubert 

Well, from a technical POV, it won't be a thing to change the return value. There's not specific reason for the current value to be `void`, it's just historical.

But on the other hand I doubt that we're going to change it in the current api version. This is because we try to avoid wsdl-changes to prevent errors/misbehaviour with some specific soap-clients out there which can cause severe trouble.

Regarding your workaround: I don't see why you need to verify the deletion by performaing a `get` afterwards. As long as the deletion-call doesn't bail out with an error, the operation was succesful.

**Comment by danielneubert** [comment]
Are you sure about the delete error? I'm sure I tried deleting a folder with some element in it and the deletion didn't threw an error, which led me to the `get()` check afterwards in the first place.

I'll test that at the weekend. An error during the delete process would be OK, just not getting any information surprised me.

**Comment by usox** [comment]
> Are you sure about the delete error? I'm sure I tried deleting a folder with some element in it and the deletion didn't threw an error, which led me to the `get()` check afterwards in the first place.

Well, that's the way it's supposed to be. We try to avoid silent errors where possible :smile: 

But well - I just checked it out and discovered the fact that `void` methods also suppress errors. This is very bogus and obviously wrong, so we're going to change the type hint.
This may take some time because we've to check if this needs to be announced in the first place. We will update the client accordingly

Thank you for pointing this out.

**Comment by danielneubert** [comment]
OK, thanks for checking this out. 👍🏼

**Comment by usox** [comment]
Hi @danielneubert 

If have an update for you: We will change the typehint on 11.12.2020. The result of the connector will be changed afterwards, but the exceptions from the api won't be affected from a delayed connector update.

**Comment by danielneubert** [comment]
Hey there, thank you for the information and upcoming update. I'll stay tuned for the change. :-)

**Comment by usox** [comment]
@danielneubert
This will be released within a bugfix release of the connector.
