### ISSUE TITLE
Exceptions when accessing FormStatistics

### ISSUE THREAD

**Issue by LosHawlos** [SC-Networks/evalanche-soap-api-connector#185]
The FormStatistics returned by createFormClient()->getStatistics() seem to be incomplete, because some fields are empty.
This then throws exceptions when calling the getter methods because the type hint for the returned value does not allow null values.

> In FormStatistic.php line 148:
>   [TypeError]
>   Scn\EvalancheSoapStruct\Struct\Statistic\FormStatistic::getUrl(): Return value must be of type string, null returned

> In FormStatistic.php line 156:
>   [TypeError]
>   Scn\EvalancheSoapStruct\Struct\Statistic\FormStatistic::getTypeId(): Return value must be of type int, null returned  

> In FormStatistic.php line 164:
>   [TypeError]
>   Scn\EvalancheSoapStruct\Struct\Statistic\FormStatistic::getFolderId(): Return value must be of type int, null returned  

> In FormStatistic.php line 172:
>   [TypeError]
>   Scn\EvalancheSoapStruct\Struct\Statistic\FormStatistic::getMandatorId(): Return value must be of type int, null returned  

> In FormStatistic.php line 212:
>   [TypeError]                                                                                                                                
>   Scn\EvalancheSoapStruct\Struct\Statistic\FormStatistic::getDuplicationErrorCount(): Return value must be of type int, null returned   

At least url, typeId, folderId and mandatorId are correctly returned by createFormClient()->getById() but are not available in createFormClient()->getStatistics()

**Comment by usox** [comment]
Thanks, we'll look into it

**Comment by usox** [comment]
Ok thanks again - we have actually two separate bugs in here.

- url, type_id, folder_id and mandator_id are `extended base information` which are not provided by specialized methods like `getStatistics`. The getters for this data in `FormStatistic` have been implementeted there by mistake. We will deprecated those methods and remove them within the next major release
- duplication_error_count is currently not working because of a typo. We'll provide a fix for this asap

**Comment by usox** [comment]
@LosHawlos Ok, I released 1.10.1 which should resolve the issues.
