### ISSUE TITLE
Add method to update mailing templates

### ISSUE THREAD

**Issue by NickHatBoecker** [SC-Networks/evalanche-soap-api-connector#60]
Dear SC-Networks,

the connector is a really handy lib.
I would love to see the feature to update article- and mailing-templates.
At the moment there is only a read permission, but none for writing.

With the write permission we could implement the templates locally in our favorite IDE and put them under version control. After this we use the connector and a little bash or php script to update them in evalanche.

Thank you very much for your work!

Best regards
Nick

**Comment by usox** [comment]
This is planned for 1.6 Milestone. It will include:
- Method to create Mailing Templates
- Retrieve retrieve configuration and sourcecodes
- Update existing templates (configuration and sourcecodes)
- Apply Mailing Templates on existing Mailings

@NickHatBoecker If you have furthergoing ideas/wishes, please let us know.

**Comment by usox** [comment]
#81

**Comment by NickHatBoecker** [comment]
@usox Nice, I'm really looking forward to it!
You only mentioned mailing templates. Does this include article templates as well?

**Comment by usox** [comment]
@NickHatBoecker Yep, we separated the tasks. The Article Template enhancement will be part of the upcoming 1.5.0 release. See #81

**Comment by usox** [comment]
@NickHatBoecker fyi The new methods to update article templates has already been released in april.
https://github.com/SC-Networks/evalanche-soap-api-connector/blob/master/docs/articletemplate.md

**Comment by NickHatBoecker** [comment]
@usox Nice work, thank you! I'm looking forward to the mailing templates as well!

**Comment by usox** [comment]
@NickHatBoecker Creating new templates and applying existing templates on mailings will be the first methods to be released shortly.

**Comment by usox** [comment]
Hi @NickHatBoecker 

We finished integrating the connector-methods for the MailingTemplate namespace. If you'd like, you can test the current implementation by using `dev-master` als version constraint in your composer-config. The methods are accessible by using the `MailingTemplateClient`.
Building the result of some methods may fail because we have to alter the results of two methods in the api - this will be released next week.

**But beware: This has not been officially released yet so use it at your own risk. It would be wise to not use it in production-environments.**

The release 1.6 of the connector - which will contain the MailingTemplate methods - will take place in october.

cu

**Comment by usox** [comment]
Support for MailingTemplates has been released within version 1.6 today.
